#!/usr/bin/env python
from . import bp
from flask import redirect, session, current_app, url_for, request
import requests
from urllib.parse import urlencode
import secrets

def authz_url() -> str:
   state = secrets.token_urlsafe(32)   # secure random string
   session["oauth_state"] = state     # store in session
   # session["oauth_state"] = current_app.config['STATE_FIXED']
   params = {
       "response_type": "code",
       "client_id": current_app.config['CLIENT_ID'],
       "redirect_uri": current_app.config['REDIRECT_URI'],
       "scope": current_app.config['SCOPES'],
       "state": state, #current_app.config['STATE_FIXED'],
       #"state": current_app.config['STATE_FIXED'],
   }
   return f"{current_app.config['AUTH_URL']}?{urlencode(params)}"


@bp.route('/login')
def login():
   session.pop("last_error", None)
   url = authz_url()
   print(url)
   print("[DEBUG] CLIENT_ID repr:", repr(current_app.config['CLIENT_ID']))
   print("[DEBUG] AUTH URL:", url)
   return redirect(url)


@bp.route('/callback')
def callback():

    # make sure state returned is the same that was originally provided
    returned_state = request.args.get("state")
    original_state = session.get("oauth_state")

    if not returned_state or returned_state != original_state:
        return "Invalid state parameter", 400
    
    session.pop("oauth_state", None) # clear state once verified

    code = request.args.get("code") # generated by the OAuth authorization server

    if not code:
        session["last_error"] = "No code returned"
        return redirect(url_for("main.index"))

    # Exchange code for access token
    token_response = requests.post(
        current_app.config["TOKEN_URL"],
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": current_app.config["REDIRECT_URI"],
            "client_id": current_app.config["CLIENT_ID"],
            "client_secret": current_app.config["CLIENT_SECRET"],
        },
    )

    token_json = token_response.json()
    # print(token_json)

    if "access_token" not in token_json:
        session["last_error"] = "Token exchange failed"
        return redirect(url_for("main.index"))

    # save the access token in session so we know the user is logged in
    session["access_token"] = token_json["access_token"]

    return redirect(url_for("main.index"))


@bp.route('/logout')
def logout():
   session.pop("access_token", None)
   return redirect(url_for("main.index"))


def is_logged_in():
   return "access_token" in session